
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: search-impersonator
rules:
- apiGroups: [""]
  resources: ["users", "serviceaccounts", "groups"] 
  verbs: ["impersonate"]

